language: python

cache: pip
dist: bionic
group: edge

python:
    - "3.6"
    - "3.6-dev"
    - "3.7"
    - "3.7-dev"
    - "nightly"

install:
    - pip install pipenv
    - pipenv install -d

script:
    - pipenv run nosetests-3.4 -s --with-coverage --cover-package=pycvesearch

after_success:
    - codecov
    - coveralls
