language: python

cache: pip
dist: bionic
group: edge

python:
    - "3.6"
    - "3.6-dev"
    - "3.7"
    - "3.7-dev"
    - "nightly"

install:
    - pip install coveralls
    - pip install codecov
    - pip install .

script:
    - nosetests --with-coverage --cover-package=pycvesearch

after_success:
    - codecov
    - coveralls
